#!/usr/bin/bash

startOnce() {
  if [ $(which "$1") ]; then
    [ pidof "$1" ] || "$@" &
  fi
  sleep 0.3s
}

set_rule() {
  case "$1" in
    float|floating)
      for window in $2
      do bspc rule --add $window state=floating follow=on
      done
    ;;
    todesk|workspace)
      for window in $3
      do bspc rule --add $window desktop=$2 follow=on
      done
    ;;
    *) echo "BSPWM CONFIG: Bad argument"
    ;;
  esac
}

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 4
bspc config window_gap 8

bspc config split_ratio 0.6

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config focus_follows_pointer true

bspc config normal_border_color "#908caa"
bspc config focused_border_color "#9ccfd8"
bspc config active_border_color "#DE6E7C"

set_rule "floating" "Thunar Pcmanfm Places vlc mpv Gimp Popup Nitrogen Xfce4-panel Xarchiver feh Protonvpn lxapperance seahorse"
set_rule "todesk" "2" "Firefox Firefox-esr Google-chrome brave microsoft-edge"
set_rule "todesk" "5" "crx_cinhimbnkkaeohfgghhklpknlkffjgod" # google chrome yt music
set_rule "todesk" "6" "obs"

#### autostart applications
# startOnce /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
startOnce /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 # on debian
startOnce /usr/libexec/xdg-desktop-portal
startOnce /usr/libexec/xdg-desktop-portal-gtk
startOnce nitrogen --restore
startOnce sxhkd
startOnce picom --experimental-backends
startOnce polybar
startOnce dunst
