#!/usr/bin/bash

startOnce() {
  [ pgrep $1 ] || "$@" &
  sleep 0.3s
}

set_rule() {
  case "$1" in
    float|floating)
      for window in $2
      do bspc rule --add $window state=floating follow=on
      done
    ;;
    todesk|workspace)
      for window in $3
      do bspc rule --add $window desktop=$2 follow=on
      done
    ;;
    *) echo "BSPWM CONFIG: Bad argument"
    ;;
  esac
}

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 4
bspc config window_gap 8

bspc config split_ratio 0.6

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config focus_follows_pointer false

bspc config normal_border_color "#908caa"
bspc config focused_border_color "#9ccfd8"
bspc config active_border_color "#DE6E7C"

set_rule "floating" "Thunar Pcmanfm Places vlc mpv Gimp Rofi Popup Nitrogen Xfce4-panel Xarchiver feh Protonvpn"
set_rule "todesk" "2" "firefox Google-chrome brave microsoft-edge"
set_rule "todesk" "5" "crx_cinhimbnkkaeohfgghhklpknlkffjgod" # google chrome yt music
set_rule "todesk" "6" "obs"

#### autostart applications
nitrogen --restore
startOnce sxhkd
startOnce polybar
startOnce dunst
startOnce picom
startOnce /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
startOnce bspswallow
# YOU CAN INSTALL THE FOLLOWING APPS
# AND UNCOMMENT THEM BUT I DON'T USE THEM OFTEN
# startOnce xfsettingsd --disable-wm-check
# startOnce nm-applet
#
# NEEDED FOR KEYRING
dbus-update-activation-environment --all &
gnome-keyring-daemon --start --components=secrets &
